default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: MyP@ssw0rd!
  host: localhost

development:
  <<: *default
  database: auth_users_development

test:
  <<: *default
  database: auth_users_test

production:
  <<: *default
  database: auth_users_production
  username: auth_users
  password: <%= ENV['AUTH_USERS_DATABASE_PASSWORD']%>